/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package monopoly;

import java.util.ArrayList;
import javax.swing.JButton;

/**
 * Receives the list of people player and the list of properties. Allows 
 * the user to check who owns what.
 * @author c0621990 - Kyle Crossman
 * @Date December 3 2014
 */
public class OwnedProperties extends javax.swing.JFrame {
    ArrayList<Player> PlayerGroup;
    Property[] BoardProperties;
    
    /**
     * Creates new form OwnedProperties
     */
    public OwnedProperties(ArrayList<Player> PG, Property[] BP) {
        initComponents();
        PlayerGroup = PG;
        BoardProperties = BP;
        
        refreshButtons();
    }

    /**
     * Displays the products owned by which player was clicked.
     * 
     * @param PlayerToView The player's number that is being looked at.
     */
    public void displayProperties(int PlayerToView) {
        String PropOwnedString = "";
        int[] PropOwned = PlayerGroup.get(PlayerToView).GetLocationsOwned();
        
        PropOwnedString += "<html>";
        //Loops through all of the properties.
        for (int i = 0; i < PropOwned.length; i++) {
            //Checks to see if the player owns the property.
            if (PropOwned[i] == 1) {
                if (BoardProperties[i].GetPropertyType().equals("RR")) {
                    PropOwnedString += BoardProperties[i].GetPropertyName() + " Tax Amount - $" + BoardProperties[i].GetPropertyTax() * PlayerGroup.get(PlayerToView).GetRailroadMultiplier();
                }
                else {
                    PropOwnedString += BoardProperties[i].GetPropertyName() + " Tax Amount - $" + BoardProperties[i].GetPropertyTax();
                }
                PropOwnedString += "<br/>";
            }
        }
        PropOwnedString += "</html>";
        
        //Output the properties that the player owns.
        PropertiesOwnedLabel.setText(PropOwnedString);
    }
    
    /**
     * Hides and sets the names of the player buttons. Will hide buttons until there are the correct
     * amount for the current amount of players.
     */
    public void refreshButtons() {
        JButton[] arrayOfButtons = {PlayerOneButton, PlayerTwoButton, PlayerThreeButton, PlayerFourButton};

        //Hides all of the buttons not needed.
        for (int i = 3; i >= PlayerGroup.size(); i--) {
            arrayOfButtons[i].setVisible(false);
        }
        //Change all of the text of buttons being used.
        for (int i = 0; i < PlayerGroup.size(); i++) {
            arrayOfButtons[i].setText(PlayerGroup.get(i).GetPlayerName());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDisplay = new javax.swing.JPanel();
        PlayerNameLabel = new javax.swing.JLabel();
        PlayerOneButton = new javax.swing.JButton();
        PlayerTwoButton = new javax.swing.JButton();
        PlayerThreeButton = new javax.swing.JButton();
        PlayerFourButton = new javax.swing.JButton();
        PropOwnedIdentifier = new javax.swing.JLabel();
        PropertiesOwnedLabel = new javax.swing.JLabel();

        PlayerNameLabel.setText("Player To View");

        PlayerOneButton.setText("NAME");
        PlayerOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerOneButtonActionPerformed(evt);
            }
        });

        PlayerTwoButton.setText("NAME");
        PlayerTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerTwoButtonActionPerformed(evt);
            }
        });

        PlayerThreeButton.setText("NAME");
        PlayerThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerThreeButtonActionPerformed(evt);
            }
        });

        PlayerFourButton.setText("NAME");
        PlayerFourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerFourButtonActionPerformed(evt);
            }
        });

        PropOwnedIdentifier.setText("Properties Owned");

        javax.swing.GroupLayout panelDisplayLayout = new javax.swing.GroupLayout(panelDisplay);
        panelDisplay.setLayout(panelDisplayLayout);
        panelDisplayLayout.setHorizontalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisplayLayout.createSequentialGroup()
                .addComponent(PropOwnedIdentifier)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelDisplayLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PlayerFourButton)
                        .addComponent(PlayerThreeButton))
                    .addComponent(PlayerTwoButton)
                    .addGroup(panelDisplayLayout.createSequentialGroup()
                        .addComponent(PlayerNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(PlayerOneButton)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panelDisplayLayout.setVerticalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisplayLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerNameLabel)
                    .addComponent(PlayerOneButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PlayerTwoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PlayerThreeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PlayerFourButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(PropOwnedIdentifier))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PropertiesOwnedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PropertiesOwnedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayerOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerOneButtonActionPerformed
        displayProperties(0);
    }//GEN-LAST:event_PlayerOneButtonActionPerformed

    private void PlayerTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerTwoButtonActionPerformed
        displayProperties(1);
    }//GEN-LAST:event_PlayerTwoButtonActionPerformed

    private void PlayerThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerThreeButtonActionPerformed
        displayProperties(2);
    }//GEN-LAST:event_PlayerThreeButtonActionPerformed

    private void PlayerFourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerFourButtonActionPerformed
        displayProperties(3);
    }//GEN-LAST:event_PlayerFourButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnedProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnedProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnedProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnedProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlayerFourButton;
    private javax.swing.JLabel PlayerNameLabel;
    private javax.swing.JButton PlayerOneButton;
    private javax.swing.JButton PlayerThreeButton;
    private javax.swing.JButton PlayerTwoButton;
    private javax.swing.JLabel PropOwnedIdentifier;
    private javax.swing.JLabel PropertiesOwnedLabel;
    private javax.swing.JPanel panelDisplay;
    // End of variables declaration//GEN-END:variables
}
